import type { LucideIcon } from "lucide-react";
import {
  Utensils, Home, Car, Bus, Fuel, Film, Gamepad2, Music, Popcorn,
  HeartPulse, Pill, Stethoscope, GraduationCap, BookOpen, Shirt,
  ShoppingBag, ShoppingCart, Gift, Plane, Hotel, PawPrint, Dog, Cat,
  Smartphone, Laptop, Wifi, Tv, Scissors, Sparkles, Dumbbell, Baby,
  Users, Wrench, Hammer, Zap, Droplet, Flame, CreditCard, Receipt,
  Landmark, FileText, HandHeart, Church, Coffee, Beer, Wine, Bike,
  TrainFront, Building2, Umbrella, ShieldCheck, PiggyBank, Percent,
  AlertCircle, Briefcase, Wallet, TrendingUp, HandCoins, Coins,
  Banknote, DollarSign, ArrowDownToLine, Building, Award, Star,
  Palette, Camera, Cake, Trees, Flower2, Sun, Snowflake, Package,
} from "lucide-react";

/**
 * Lista ampla de ícones pra categorias financeiras — qualquer um vale
 * pra receita ou despesa, sem separação rígida (a pessoa escolhe o
 * que fizer mais sentido pra ela).
 */
export const ICONES_CATEGORIA: { nome: string; Icone: LucideIcon }[] = [
  { nome: "Utensils", Icone: Utensils },
  { nome: "Home", Icone: Home },
  { nome: "Car", Icone: Car },
  { nome: "Bus", Icone: Bus },
  { nome: "Fuel", Icone: Fuel },
  { nome: "Bike", Icone: Bike },
  { nome: "TrainFront", Icone: TrainFront },
  { nome: "Film", Icone: Film },
  { nome: "Gamepad2", Icone: Gamepad2 },
  { nome: "Music", Icone: Music },
  { nome: "Popcorn", Icone: Popcorn },
  { nome: "HeartPulse", Icone: HeartPulse },
  { nome: "Pill", Icone: Pill },
  { nome: "Stethoscope", Icone: Stethoscope },
  { nome: "GraduationCap", Icone: GraduationCap },
  { nome: "BookOpen", Icone: BookOpen },
  { nome: "Shirt", Icone: Shirt },
  { nome: "ShoppingBag", Icone: ShoppingBag },
  { nome: "ShoppingCart", Icone: ShoppingCart },
  { nome: "Gift", Icone: Gift },
  { nome: "Plane", Icone: Plane },
  { nome: "Hotel", Icone: Hotel },
  { nome: "PawPrint", Icone: PawPrint },
  { nome: "Dog", Icone: Dog },
  { nome: "Cat", Icone: Cat },
  { nome: "Smartphone", Icone: Smartphone },
  { nome: "Laptop", Icone: Laptop },
  { nome: "Wifi", Icone: Wifi },
  { nome: "Tv", Icone: Tv },
  { nome: "Scissors", Icone: Scissors },
  { nome: "Sparkles", Icone: Sparkles },
  { nome: "Dumbbell", Icone: Dumbbell },
  { nome: "Baby", Icone: Baby },
  { nome: "Users", Icone: Users },
  { nome: "Wrench", Icone: Wrench },
  { nome: "Hammer", Icone: Hammer },
  { nome: "Zap", Icone: Zap },
  { nome: "Droplet", Icone: Droplet },
  { nome: "Flame", Icone: Flame },
  { nome: "CreditCard", Icone: CreditCard },
  { nome: "Receipt", Icone: Receipt },
  { nome: "Landmark", Icone: Landmark },
  { nome: "FileText", Icone: FileText },
  { nome: "HandHeart", Icone: HandHeart },
  { nome: "Church", Icone: Church },
  { nome: "Coffee", Icone: Coffee },
  { nome: "Beer", Icone: Beer },
  { nome: "Wine", Icone: Wine },
  { nome: "Building2", Icone: Building2 },
  { nome: "Building", Icone: Building },
  { nome: "Umbrella", Icone: Umbrella },
  { nome: "ShieldCheck", Icone: ShieldCheck },
  { nome: "PiggyBank", Icone: PiggyBank },
  { nome: "Percent", Icone: Percent },
  { nome: "AlertCircle", Icone: AlertCircle },
  { nome: "Briefcase", Icone: Briefcase },
  { nome: "Wallet", Icone: Wallet },
  { nome: "TrendingUp", Icone: TrendingUp },
  { nome: "HandCoins", Icone: HandCoins },
  { nome: "Coins", Icone: Coins },
  { nome: "Banknote", Icone: Banknote },
  { nome: "DollarSign", Icone: DollarSign },
  { nome: "ArrowDownToLine", Icone: ArrowDownToLine },
  { nome: "Award", Icone: Award },
  { nome: "Star", Icone: Star },
  { nome: "Palette", Icone: Palette },
  { nome: "Camera", Icone: Camera },
  { nome: "Cake", Icone: Cake },
  { nome: "Trees", Icone: Trees },
  { nome: "Flower2", Icone: Flower2 },
  { nome: "Sun", Icone: Sun },
  { nome: "Snowflake", Icone: Snowflake },
  { nome: "Package", Icone: Package },
];

export const MAPA_ICONES_CATEGORIA = new Map(ICONES_CATEGORIA.map((i) => [i.nome, i.Icone]));
