import type { LucideIcon } from "lucide-react";
import {
  Utensils, Pizza, Sandwich, Soup, Beef, Drumstick, Fish, Egg,
  Croissant, Cookie, IceCreamCone, Candy, Apple, Banana, Carrot, Salad,
  Coffee, CupSoda, Milk, Beer, Wine, Martini, Home, Sofa,
  Bed, Lamp, Key, Bath, ShowerHead, WashingMachine, Plug, Lightbulb,
  Zap, Droplet, Flame, Wifi, Router, Tv, Phone, Smartphone,
  Laptop, Monitor, Car, Fuel, CircleParking, Bus, TrainFront, Bike,
  Truck, Plane, Ship, Luggage, Hotel, Tent, Mountain, MapPin,
  HeartPulse, Pill, Syringe, Stethoscope, Hospital, Ambulance, Glasses, Brain,
  Smile, Dumbbell, Activity, Scissors, Sparkles, GraduationCap, School, BookOpen,
  Backpack, Pencil, Calculator, Newspaper, Languages, Film, Clapperboard, Popcorn,
  Gamepad2, Dices, Puzzle, Music, Guitar, Mic, Headphones, Ticket,
  Camera, Palette, Paintbrush, PartyPopper, Trophy, Shirt, ShoppingBag, ShoppingCart,
  Store, Tag, Gift, Gem, Watch, Package, ToyBrick, Baby,
  Users, HeartHandshake, HandHeart, Church, PawPrint, Dog, Cat, Bird,
  Rabbit, Bone, Wrench, Hammer, Construction, Shovel, Leaf, Trees,
  Flower2, Sprout, Recycle, Sun, Snowflake, Umbrella, ShieldCheck, CreditCard,
  Receipt, ReceiptText, FileText, Landmark, Scale, Gavel, Percent, BadgePercent,
  AlertCircle, Cigarette, Briefcase, Building, Building2, Factory, Wallet, PiggyBank,
  TrendingUp, ChartLine, HandCoins, Coins, Banknote, DollarSign, ArrowDownToLine, Handshake,
  Award, Star, Cake, Crown, Rocket,
} from "lucide-react";

/**
 * Lista ampla de ícones pra categorias financeiras — qualquer um vale
 * pra receita ou despesa. Etapa 272: bem mais opções, agrupadas por
 * assunto (comida, casa, transporte, saúde...). A ordem dos primeiros
 * não importa pra quem já tem categoria: o banco guarda o NOME do ícone.
 */
export const ICONES_CATEGORIA: { nome: string; Icone: LucideIcon }[] = [
  { nome: "Utensils", Icone: Utensils },
  { nome: "Pizza", Icone: Pizza },
  { nome: "Sandwich", Icone: Sandwich },
  { nome: "Soup", Icone: Soup },
  { nome: "Beef", Icone: Beef },
  { nome: "Drumstick", Icone: Drumstick },
  { nome: "Fish", Icone: Fish },
  { nome: "Egg", Icone: Egg },
  { nome: "Croissant", Icone: Croissant },
  { nome: "Cookie", Icone: Cookie },
  { nome: "IceCreamCone", Icone: IceCreamCone },
  { nome: "Candy", Icone: Candy },
  { nome: "Apple", Icone: Apple },
  { nome: "Banana", Icone: Banana },
  { nome: "Carrot", Icone: Carrot },
  { nome: "Salad", Icone: Salad },
  { nome: "Coffee", Icone: Coffee },
  { nome: "CupSoda", Icone: CupSoda },
  { nome: "Milk", Icone: Milk },
  { nome: "Beer", Icone: Beer },
  { nome: "Wine", Icone: Wine },
  { nome: "Martini", Icone: Martini },
  { nome: "Home", Icone: Home },
  { nome: "Sofa", Icone: Sofa },
  { nome: "Bed", Icone: Bed },
  { nome: "Lamp", Icone: Lamp },
  { nome: "Key", Icone: Key },
  { nome: "Bath", Icone: Bath },
  { nome: "ShowerHead", Icone: ShowerHead },
  { nome: "WashingMachine", Icone: WashingMachine },
  { nome: "Plug", Icone: Plug },
  { nome: "Lightbulb", Icone: Lightbulb },
  { nome: "Zap", Icone: Zap },
  { nome: "Droplet", Icone: Droplet },
  { nome: "Flame", Icone: Flame },
  { nome: "Wifi", Icone: Wifi },
  { nome: "Router", Icone: Router },
  { nome: "Tv", Icone: Tv },
  { nome: "Phone", Icone: Phone },
  { nome: "Smartphone", Icone: Smartphone },
  { nome: "Laptop", Icone: Laptop },
  { nome: "Monitor", Icone: Monitor },
  { nome: "Car", Icone: Car },
  { nome: "Fuel", Icone: Fuel },
  { nome: "CircleParking", Icone: CircleParking },
  { nome: "Bus", Icone: Bus },
  { nome: "TrainFront", Icone: TrainFront },
  { nome: "Bike", Icone: Bike },
  { nome: "Truck", Icone: Truck },
  { nome: "Plane", Icone: Plane },
  { nome: "Ship", Icone: Ship },
  { nome: "Luggage", Icone: Luggage },
  { nome: "Hotel", Icone: Hotel },
  { nome: "Tent", Icone: Tent },
  { nome: "Mountain", Icone: Mountain },
  { nome: "MapPin", Icone: MapPin },
  { nome: "HeartPulse", Icone: HeartPulse },
  { nome: "Pill", Icone: Pill },
  { nome: "Syringe", Icone: Syringe },
  { nome: "Stethoscope", Icone: Stethoscope },
  { nome: "Hospital", Icone: Hospital },
  { nome: "Ambulance", Icone: Ambulance },
  { nome: "Glasses", Icone: Glasses },
  { nome: "Brain", Icone: Brain },
  { nome: "Smile", Icone: Smile },
  { nome: "Dumbbell", Icone: Dumbbell },
  { nome: "Activity", Icone: Activity },
  { nome: "Scissors", Icone: Scissors },
  { nome: "Sparkles", Icone: Sparkles },
  { nome: "GraduationCap", Icone: GraduationCap },
  { nome: "School", Icone: School },
  { nome: "BookOpen", Icone: BookOpen },
  { nome: "Backpack", Icone: Backpack },
  { nome: "Pencil", Icone: Pencil },
  { nome: "Calculator", Icone: Calculator },
  { nome: "Newspaper", Icone: Newspaper },
  { nome: "Languages", Icone: Languages },
  { nome: "Film", Icone: Film },
  { nome: "Clapperboard", Icone: Clapperboard },
  { nome: "Popcorn", Icone: Popcorn },
  { nome: "Gamepad2", Icone: Gamepad2 },
  { nome: "Dices", Icone: Dices },
  { nome: "Puzzle", Icone: Puzzle },
  { nome: "Music", Icone: Music },
  { nome: "Guitar", Icone: Guitar },
  { nome: "Mic", Icone: Mic },
  { nome: "Headphones", Icone: Headphones },
  { nome: "Ticket", Icone: Ticket },
  { nome: "Camera", Icone: Camera },
  { nome: "Palette", Icone: Palette },
  { nome: "Paintbrush", Icone: Paintbrush },
  { nome: "PartyPopper", Icone: PartyPopper },
  { nome: "Trophy", Icone: Trophy },
  { nome: "Shirt", Icone: Shirt },
  { nome: "ShoppingBag", Icone: ShoppingBag },
  { nome: "ShoppingCart", Icone: ShoppingCart },
  { nome: "Store", Icone: Store },
  { nome: "Tag", Icone: Tag },
  { nome: "Gift", Icone: Gift },
  { nome: "Gem", Icone: Gem },
  { nome: "Watch", Icone: Watch },
  { nome: "Package", Icone: Package },
  { nome: "ToyBrick", Icone: ToyBrick },
  { nome: "Baby", Icone: Baby },
  { nome: "Users", Icone: Users },
  { nome: "HeartHandshake", Icone: HeartHandshake },
  { nome: "HandHeart", Icone: HandHeart },
  { nome: "Church", Icone: Church },
  { nome: "PawPrint", Icone: PawPrint },
  { nome: "Dog", Icone: Dog },
  { nome: "Cat", Icone: Cat },
  { nome: "Bird", Icone: Bird },
  { nome: "Rabbit", Icone: Rabbit },
  { nome: "Bone", Icone: Bone },
  { nome: "Wrench", Icone: Wrench },
  { nome: "Hammer", Icone: Hammer },
  { nome: "Construction", Icone: Construction },
  { nome: "Shovel", Icone: Shovel },
  { nome: "Leaf", Icone: Leaf },
  { nome: "Trees", Icone: Trees },
  { nome: "Flower2", Icone: Flower2 },
  { nome: "Sprout", Icone: Sprout },
  { nome: "Recycle", Icone: Recycle },
  { nome: "Sun", Icone: Sun },
  { nome: "Snowflake", Icone: Snowflake },
  { nome: "Umbrella", Icone: Umbrella },
  { nome: "ShieldCheck", Icone: ShieldCheck },
  { nome: "CreditCard", Icone: CreditCard },
  { nome: "Receipt", Icone: Receipt },
  { nome: "ReceiptText", Icone: ReceiptText },
  { nome: "FileText", Icone: FileText },
  { nome: "Landmark", Icone: Landmark },
  { nome: "Scale", Icone: Scale },
  { nome: "Gavel", Icone: Gavel },
  { nome: "Percent", Icone: Percent },
  { nome: "BadgePercent", Icone: BadgePercent },
  { nome: "AlertCircle", Icone: AlertCircle },
  { nome: "Cigarette", Icone: Cigarette },
  { nome: "Briefcase", Icone: Briefcase },
  { nome: "Building", Icone: Building },
  { nome: "Building2", Icone: Building2 },
  { nome: "Factory", Icone: Factory },
  { nome: "Wallet", Icone: Wallet },
  { nome: "PiggyBank", Icone: PiggyBank },
  { nome: "TrendingUp", Icone: TrendingUp },
  { nome: "ChartLine", Icone: ChartLine },
  { nome: "HandCoins", Icone: HandCoins },
  { nome: "Coins", Icone: Coins },
  { nome: "Banknote", Icone: Banknote },
  { nome: "DollarSign", Icone: DollarSign },
  { nome: "ArrowDownToLine", Icone: ArrowDownToLine },
  { nome: "Handshake", Icone: Handshake },
  { nome: "Award", Icone: Award },
  { nome: "Star", Icone: Star },
  { nome: "Cake", Icone: Cake },
  { nome: "Crown", Icone: Crown },
  { nome: "Rocket", Icone: Rocket },
];

export const MAPA_ICONES_CATEGORIA = new Map(ICONES_CATEGORIA.map((i) => [i.nome, i.Icone]));
