import type { LucideIcon } from "lucide-react";
import {
  Droplet, GlassWater, Footprints, PersonStanding, Dumbbell, Bike, Volleyball, Waves,
  Activity, HeartPulse, Pill, Apple, Salad, Carrot, Moon, Bed,
  Sunrise, Sun, AlarmClock, Timer, Hourglass, BookOpen, Library, NotebookPen,
  PenLine, GraduationCap, Languages, Brain, Code, Laptop, Target, ListChecks,
  CircleCheck, Flower2, Sprout, Leaf, Trees, Mountain, Smile, Heart,
  HandHeart, Church, Sparkles, Wind, Brush, ShowerHead, Bath, Shirt,
  WashingMachine, ChefHat, Utensils, Home, Trash2, Music2, Guitar, Piano,
  Mic, Headphones, Palette, Camera, Gamepad2, Tv, Users, Phone,
  MessageCircle, Mail, Baby, PawPrint, Dog, Cat, Coins, PiggyBank,
  Wallet, Briefcase, Coffee, Ban, PhoneOff, CigaretteOff, WineOff, Plus,
  Star, Trophy, Flame, Zap, Rocket,
} from "lucide-react";

/**
 * Ícones de hábitos e tarefas. Etapa 272: mais opções (sono, água,
 * estudo, casa, música, "parar de"...). O banco guarda o NOME.
 */
export const ICONES_HABITO: { nome: string; Icone: LucideIcon }[] = [
  { nome: "Droplet", Icone: Droplet },
  { nome: "GlassWater", Icone: GlassWater },
  { nome: "Footprints", Icone: Footprints },
  { nome: "PersonStanding", Icone: PersonStanding },
  { nome: "Dumbbell", Icone: Dumbbell },
  { nome: "Bike", Icone: Bike },
  { nome: "Volleyball", Icone: Volleyball },
  { nome: "Waves", Icone: Waves },
  { nome: "Activity", Icone: Activity },
  { nome: "HeartPulse", Icone: HeartPulse },
  { nome: "Pill", Icone: Pill },
  { nome: "Apple", Icone: Apple },
  { nome: "Salad", Icone: Salad },
  { nome: "Carrot", Icone: Carrot },
  { nome: "Moon", Icone: Moon },
  { nome: "Bed", Icone: Bed },
  { nome: "Sunrise", Icone: Sunrise },
  { nome: "Sun", Icone: Sun },
  { nome: "AlarmClock", Icone: AlarmClock },
  { nome: "Timer", Icone: Timer },
  { nome: "Hourglass", Icone: Hourglass },
  { nome: "BookOpen", Icone: BookOpen },
  { nome: "Library", Icone: Library },
  { nome: "NotebookPen", Icone: NotebookPen },
  { nome: "PenLine", Icone: PenLine },
  { nome: "GraduationCap", Icone: GraduationCap },
  { nome: "Languages", Icone: Languages },
  { nome: "Brain", Icone: Brain },
  { nome: "Code", Icone: Code },
  { nome: "Laptop", Icone: Laptop },
  { nome: "Target", Icone: Target },
  { nome: "ListChecks", Icone: ListChecks },
  { nome: "CircleCheck", Icone: CircleCheck },
  { nome: "Flower2", Icone: Flower2 },
  { nome: "Sprout", Icone: Sprout },
  { nome: "Leaf", Icone: Leaf },
  { nome: "Trees", Icone: Trees },
  { nome: "Mountain", Icone: Mountain },
  { nome: "Smile", Icone: Smile },
  { nome: "Heart", Icone: Heart },
  { nome: "HandHeart", Icone: HandHeart },
  { nome: "Church", Icone: Church },
  { nome: "Sparkles", Icone: Sparkles },
  { nome: "Wind", Icone: Wind },
  { nome: "Brush", Icone: Brush },
  { nome: "ShowerHead", Icone: ShowerHead },
  { nome: "Bath", Icone: Bath },
  { nome: "Shirt", Icone: Shirt },
  { nome: "WashingMachine", Icone: WashingMachine },
  { nome: "ChefHat", Icone: ChefHat },
  { nome: "Utensils", Icone: Utensils },
  { nome: "Home", Icone: Home },
  { nome: "Trash2", Icone: Trash2 },
  { nome: "Music2", Icone: Music2 },
  { nome: "Guitar", Icone: Guitar },
  { nome: "Piano", Icone: Piano },
  { nome: "Mic", Icone: Mic },
  { nome: "Headphones", Icone: Headphones },
  { nome: "Palette", Icone: Palette },
  { nome: "Camera", Icone: Camera },
  { nome: "Gamepad2", Icone: Gamepad2 },
  { nome: "Tv", Icone: Tv },
  { nome: "Users", Icone: Users },
  { nome: "Phone", Icone: Phone },
  { nome: "MessageCircle", Icone: MessageCircle },
  { nome: "Mail", Icone: Mail },
  { nome: "Baby", Icone: Baby },
  { nome: "PawPrint", Icone: PawPrint },
  { nome: "Dog", Icone: Dog },
  { nome: "Cat", Icone: Cat },
  { nome: "Coins", Icone: Coins },
  { nome: "PiggyBank", Icone: PiggyBank },
  { nome: "Wallet", Icone: Wallet },
  { nome: "Briefcase", Icone: Briefcase },
  { nome: "Coffee", Icone: Coffee },
  { nome: "Ban", Icone: Ban },
  { nome: "PhoneOff", Icone: PhoneOff },
  { nome: "CigaretteOff", Icone: CigaretteOff },
  { nome: "WineOff", Icone: WineOff },
  { nome: "Plus", Icone: Plus },
  { nome: "Star", Icone: Star },
  { nome: "Trophy", Icone: Trophy },
  { nome: "Flame", Icone: Flame },
  { nome: "Zap", Icone: Zap },
  { nome: "Rocket", Icone: Rocket },
];

export const MAPA_ICONES_HABITO = new Map(ICONES_HABITO.map((i) => [i.nome, i.Icone]));
